// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRuPVlX2AIiBzVFG7a9ZW9dC9BIEs3djg',
    appId: '1:214032957113:web:6a2b128e6af3a009372568',
    messagingSenderId: '214032957113',
    projectId: 'cripto-list-app',
    authDomain: 'cripto-list-app.firebaseapp.com',
    storageBucket: 'cripto-list-app.firebasestorage.app',
    measurementId: 'G-SDD1L24X6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBL1lX1S32zFgRMd0X81TfnpltRC9K_PQ',
    appId: '1:214032957113:android:a2d60c0bb75a2e8a372568',
    messagingSenderId: '214032957113',
    projectId: 'cripto-list-app',
    storageBucket: 'cripto-list-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgnB_L6A3owgZxCZjSDDt4qZUg54QQ3vQ',
    appId: '1:214032957113:ios:47ffe979cc9e32e7372568',
    messagingSenderId: '214032957113',
    projectId: 'cripto-list-app',
    storageBucket: 'cripto-list-app.firebasestorage.app',
    iosBundleId: 'com.cryptogusy.crypto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgnB_L6A3owgZxCZjSDDt4qZUg54QQ3vQ',
    appId: '1:214032957113:ios:47ffe979cc9e32e7372568',
    messagingSenderId: '214032957113',
    projectId: 'cripto-list-app',
    storageBucket: 'cripto-list-app.firebasestorage.app',
    iosBundleId: 'com.cryptogusy.crypto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRuPVlX2AIiBzVFG7a9ZW9dC9BIEs3djg',
    appId: '1:214032957113:web:15c74939233fc191372568',
    messagingSenderId: '214032957113',
    projectId: 'cripto-list-app',
    authDomain: 'cripto-list-app.firebaseapp.com',
    storageBucket: 'cripto-list-app.firebasestorage.app',
    measurementId: 'G-C5JXK3DXK2',
  );
}